version: '3'
services:
  shop_api:
    container_name: "web"
    build:
      context: .
    command: sh /app/entrypoint.sh
    ports:
      - "7000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - back_media:/app/media
      - back_static:/app/static
    depends_on:
      - shop_api_db
      - redis
  shop_api_db:
    container_name: "db"
    image: "postgres:14"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - 'shop_api_db-data:/var/lib/postgresql/data'
  redis:
    container_name: "rediska"
    image: redis:7
    volumes:
      - redis-data:/data
  celery-worker:
    container_name: "worker"
    build:
      context: .
    command: celery -A shop_api worker
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    container_name: "beat"
    build:
      context: .
    command: celery -A shop_api beat
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-flower:
    container_name: "flower"
    build:
      context: .
    command: celery -A shop_api flower
    ports:
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    
  nginx:
    container_name: "nginx"
    image: nginx:1.25
    ports:
      - "80:80"
    depends_on:
      - shop_api
    volumes:
      - ./nginx.conf:/etс/nginx/conf.d/default.conf
      - back_media:/app/media
      - back_static:/app/static

volumes:
  shop_api_db-data:
  redis-data:
  back_media:
  back_static: